In [12]:
import pandas as pd 
import numpy as np

# Load data

In [4]:
df_covid_agg=pd.read_csv("data/user_type.csv")
node_dict = dict(zip(df_covid_agg['User ID'],df_covid_agg['y']))
all_nb = pd.read_csv("data/all_neighbor.csv")
df_mg = df_covid_agg.merge(all_nb,left_on='User ID',right_on='neighbor')
df_ct =df_mg.groupby(['screen_name','y']).count().reset_index()
intersection = set(df_mg[df_mg.group=='right'].neighbor)&set(df_mg[df_mg.group=='tagged hate'].neighbor)

# Overall statistics

In here, you will see the aggregated results of proportion of hate, neutral, counter-hate users in for each group.

First is right group

In [9]:
df_mg_agg = df_mg.groupby(['group','y']).count().reset_index()
df_right = df_mg_agg[df_mg_agg['group']=='right']
df_right['total']=df_right['User ID'].sum()
df_right['perct']=df_right['User ID']/df_right['User ID'].sum()*100
df_right

<ipython-input-9-3bda5deeca1e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_right['total']=df_right['User ID'].sum()
<ipython-input-9-3bda5deeca1e>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_right['perct']=df_right['User ID']/df_right['User ID'].sum()*100

   group    y  User ID  neighbor      id  screen_name   total      perct
6  right -1.0    12364     12364   12364        12364  161327   7.663937
7  right  0.0   147526    147526  147526       147526  161327  91.445325
8  right  1.0     1437      1437    1437         1437  161327   0.890737

Second is hate group

In [10]:
df_right = df_mg_agg[df_mg_agg['group']=='tagged hate']
df_right['total']=df_right['User ID'].sum()
df_right['perct']=df_right['User ID']/df_right['User ID'].sum()*100
df_right

<ipython-input-10-fbf0dbe06207>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_right['total']=df_right['User ID'].sum()
<ipython-input-10-fbf0dbe06207>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_right['perct']=df_right['User ID']/df_right['User ID'].sum()*100

          group    y  User ID  neighbor     id  screen_name  total      perct
9   tagged hate -1.0      414       414    414          414  11131   3.719342
10  tagged hate  0.0    10666     10666  10666        10666  11131  95.822478
11  tagged hate  1.0       51        51     51           51  11131   0.458180

Third is the common neighbors of rigth and hate groups

In [8]:
df_int = pd.DataFrame({"User ID": list(intersection)})
df_int = df_int.merge(df_covid_agg)
df_int = df_int.groupby('y').count().reset_index()
df_int['total']=df_int['User ID'].sum()
df_int['perct']=df_int['User ID']/df_int['User ID'].sum()*100
df_int

     y  User ID  total      perct
0 -1.0      180   4080   4.411765
1 -0.0     3873   4080  94.926471
2  1.0       27   4080   0.661765

# Per account statistics

In here, you will see the proportion of hate, neutral, counter-hate neighbors every account has.

First, in right group

In [13]:
df_mg_agg = df_mg[df_mg.group=='right'].groupby(['screen_name','y']).count().reset_index()
df_allnb = df_mg[df_mg.group=='right'].groupby(['screen_name']).count().reset_index()\
[['screen_name','y']].rename(columns={'y':'all_neighbors'})
df_mg_agg = df_mg_agg.merge(df_allnb)
df_mg_agg['neighbor type']=df_mg_agg['y'].map({-1:'hate',0:'neutral',1:'counter-hate'})
df_mg_agg['perct']=np.round(df_mg_agg['id']/df_mg_agg['all_neighbors']*100,2)
df_mg_agg.pivot(index='screen_name',columns='neighbor type',values='perct').sort_values('hate',ascending=False)

neighbor type    counter-hate   hate  neutral
screen_name
HawleyMO                 0.78  17.64    81.59
MarshaBlackburn          0.74   9.58    89.68
michellemalkin           1.31   8.13    90.56
conservmillen            1.15   7.67    91.18
RedState                 0.92   6.17    92.91
yesnicksearcy            0.83   5.93    93.24
LarryTaunton             0.42   5.88    93.70
RepMarkGreen             0.42   5.33    94.25
DavidAFrench             1.36   4.91    93.73
carolmswain              0.67   4.63    94.70
marylene58               0.50   4.10    95.40
DrZuhdiJasser            0.48   3.70    95.82
FRCdc                    0.28   3.16    96.56
DavidBrodyCBN            0.52   2.89    96.60
BryanJFischer            0.23   2.34    97.43
GaryLBauer               0.42   1.45    98.13
PeterLaBarbera           0.21   0.98    98.81
docvanmol                0.46   0.46    99.09

Second, in hate group

In [14]:
df_mg_agg = df_mg[df_mg.group=='tagged hate'].groupby(['screen_name','y']).count().reset_index()
df_allnb = df_mg[df_mg.group=='tagged hate'].groupby(['screen_name']).count().reset_index()\
[['screen_name','y']].rename(columns={'y':'all_neighbors'})
df_mg_agg = df_mg_agg.merge(df_allnb)
df_mg_agg['neighbor type']=df_mg_agg['y'].map({-1:'hate',0:'neutral',1:'counter-hate'})
df_mg_agg['perct']=np.round(df_mg_agg['id']/df_mg_agg['all_neighbors']*100,2)
df_mg_agg.pivot(index='screen_name',columns='neighbor type',values='perct').sort_values('hate',ascending=False)

neighbor type    counter-hate  hate  neutral
screen_name
vdare                    0.56  4.87    94.57
TOOEdit                  0.47  3.51    96.02
RenaissanceHor1          0.24  2.50    97.26
PissoffEU                0.64  2.06    97.30